#!/bin/sh

dirs=*-*
case "$1" in
    "-C")
	dirs="$2"
	shift 2
	;;
    "-C"*)
	dirs="${1#-C}"
	shift
	;;
esac

echo '-*- mode: compilation -*-'
# default-directory: *

for mk in $(eval find $dirs '-maxdepth 1 -type f -name Makefile -printf "%h\n"'); do
    dir="${mk%/*}"
    echo
    (
	set -e
	cd "$dir"
	echo "* Building in $dir"
	if [ -f run.cmd ]; then
	    exec ./run.cmd nmake -l "$@"
	else
	    exec make "$@"
	fi
    )
done 2>&1 | sed --unbuffered $'s/\r$//'
echo "* Finished"
