#!/bin/bash

usage() {
    echo "usage: $0 ruby-to-install [dest-dir(/opt/local)]" 1>&2
    exit 1
}

install=true
dryrun=
unset src
until [ $# = 0 ]; do
    case "$1" in
	-u)
	    install=
	    ;;
	-n)
	    dryrun=-n
	    ;;
	-*)
	    echo "$0: unknown option $1" 1>&2
	    exit 1
	    ;;
	*)
	    if [ ! ${src+set} ]; then
		src="$1"
	    elif [ !${dest+set} ]; then
		dest="$1"
	    else
		usage
	    fi
	    ;;
    esac
    shift
done

: ${dest=/opt/local}
if [ ! -f "$src/.installed.list" ]; then
    echo "$0: $src/.installed.list not found" 1>&2
    exit 1
fi

if [ -f "$dest/bin/ruby" -a -e "$dest/bin/ruby" ]; then
    archdir="$($dest/bin/ruby --disable=gems -rrbconfig -e 'puts RbConfig::CONFIG["rubyarchdir"]')"
    tmp=$(mktemp)
    trap 'rm -f "$tmp"' 0 2
    mv "$archdir/.installed.list" "$tmp" || exit $?
    $dest/bin/ruby --disable=gems ${0%/*}/rbuninstall.rb $dryrun --destdir="$dest" "$tmp"
    rm -f "$tmp"
    trap - 0 2
fi

if [ ${dryrun:+set} ]; then
    echo "Installing $src to $dest"
elif [ $install ]; then
    cp -a --no-preserve=ownership "$src"/* "$dest" &&
    archdir="$($dest/bin/ruby --disable=gems -rrbconfig -e 'puts RbConfig::CONFIG["rubyarchdir"]')" &&
    cp "$src/.installed.list" "$archdir/"
    exit $?
fi
